<?php

add_action( 'init', 'ssc_babe_search_params', 99 );

function ssc_babe_search_params() {
	global $kc;

	$kc->add_map( array(
		'ssc_babe_search' => array(
			'name'             => __( ' SC Room Search Form', 'ssc' ),
			'icon'             => 'ssc-icon-31',
			'category'         => 'SecretLab',
			'preview_editable' => true,
//			'assets' => array(
//				'styles' => array(
//					'footer-nested-ace-css' => false,
//				),
//			),
			'params'           => array(
				'general' => array(
                    array(
                        'name' => 'orientation',
                        'label' => esc_html__( 'Form Orientation', 'ssc' ),
                        'type' => 'radio',
                        'options' => array(
                            'vert' => esc_html__( 'Vertical', 'ssc' ),
                            'horiz' => esc_html__( 'Horizontal', 'ssc' ),
                        ),
                        'value' => 'vert'
                    ),
					array(
						'name'        => 'title',
						'type'        => 'text',
						'label'       => esc_html__( 'Title', 'ssc' ),
						'admin_label' => true,
						'value' => ''
					),
					array(
						'name'        => 'date_from_label',
						'type'        => 'text',
						'label'       => esc_html__( 'Check-in label', 'ssc' ),
						'admin_label' => true,
						'value' => esc_html__( 'Check-in', 'ssc' ),
					),
					array(
						'name'        => 'date_to_label',
						'type'        => 'text',
						'label'       => esc_html__( 'Check-out label', 'ssc' ),
						'admin_label' => true,
						'value' => esc_html__( 'Check-out', 'ssc' ),
					),
					array(
						'name'        => 'guests_label',
						'type'        => 'text',
						'label'       => esc_html__( 'Guests label', 'ssc' ),
						'admin_label' => true,
						'value' => esc_html__( 'Guests', 'ssc' ),
					),
					array(
						'name'        => 'guest_text',
						'type'        => 'text',
						'label'       => esc_html__( '"Guest" text', 'ssc' ),
						'admin_label' => true,
						'value' => esc_html__( 'Guest', 'ssc' ),
					),
					array(
						'name'        => 'guests_text',
						'type'        => 'text',
						'label'       => esc_html__( '"Guests" text', 'ssc' ),
						'admin_label' => true,
						'value' => esc_html__( 'Guests', 'ssc' ),
					),
					array(
						'name'        => 'button_title',
						'type'        => 'text',
						'label'       => esc_html__( 'Button Title', 'ssc' ),
						'admin_label' => true,
						'value' => ''
					),
					array(
						'name' => 'button_svg',
						'type' => 'attach_image',
						'label' => esc_html__( 'Select SVG for button', 'ssc' ),
						'admin_label' => true,
					),
					array(
						'name' => 'el_class',
						'type' => 'text',
						'label' => esc_html__( 'Extra Class Name', 'ssc' ),
						'description' => esc_html__( 'If you wish to style particular content element differently, then use this field to add a class name and then refer to it in your CSS file.', 'ssc' ),
						'admin_label' => true,
						'value' => ''
					),
				),
				//Styling
				esc_html__( 'styling', 'ssc' ) => array(
					array(
						'name' => 'my-css',
						'label' =>  esc_html__( 'Styling', 'ssc' ),
						'type' => 'css',
						'value' => '', // remove this if you do not need a default content
						'description' => esc_html__( 'Styles', 'ssc' ),
						'options' => array(
							array(
								'screens' => "any,999,768,667,479",
								'Box' => array(
									array('property' => 'background', 'selector' => '.babe-search-form'),
									array('property' => 'display', 'label' => esc_html__( 'Display', 'ssc' ), 'selector' => '.babe-search-form'),
									array('property' => 'float', 'label' => esc_html__( 'Float', 'ssc' ), 'selector' => '.babe-search-form'),
									array('property' => 'max-width', 'label' => esc_html__( 'Max Width', 'ssc' ), 'selector' => '.babe-search-form'),
									array('property' => 'width', 'label' => esc_html__( 'Width', 'ssc' ), 'selector' => '.babe-search-form'),
									array('property' => 'height', 'label' => esc_html__( 'Height', 'ssc' ), 'selector' => '.babe-search-form'),
									array('property' => 'box-shadow', 'label' => esc_html__( 'Box Shadow', 'ssc' ), 'selector' => '.babe-search-form'),
									array('property' => 'opacity', 'label' => esc_html__( 'Opacity', 'ssc' ), 'selector' => '.babe-search-form'),
									array('property' => 'margin', 'label' => esc_html__( 'Margin', 'ssc' ), 'selector' => '.babe-search-form'),
									array('property' => 'padding', 'label' => esc_html__( 'Padding', 'ssc' ), 'selector' => '.babe-search-form'),
									array('property' => 'border', 'label' => esc_html__( 'Border', 'ssc' ), 'selector' => '.babe-search-form'),
									array('property' => 'border-radius', 'label' => esc_html__( 'Border Radius', 'ssc' ), 'selector' => '.babe-search-form'),
								),
                                'Col Wrap' => array(
                                    array('property' => 'background', 'selector' => '#search_form .input-group > div'),
                                    array('property' => 'display', 'label' => esc_html__( 'Display', 'ssc' ), 'selector' => '#search_form .input-group > div'),
                                    array('property' => 'float', 'label' => esc_html__( 'Float', 'ssc' ), 'selector' => '#search_form .input-group > div'),
                                    array('property' => 'max-width', 'label' => esc_html__( 'Max Width', 'ssc' ), 'selector' => '#search_form .input-group > div'),
                                    array('property' => 'width', 'label' => esc_html__( 'Width', 'ssc' ), 'selector' => '#search_form .input-group > div'),
                                    array('property' => 'height', 'label' => esc_html__( 'Height', 'ssc' ), 'selector' => '#search_form .input-group > div'),
                                    array('property' => 'box-shadow', 'label' => esc_html__( 'Box Shadow', 'ssc' ), 'selector' => '#search_form .input-group > div'),
                                    array('property' => 'opacity', 'label' => esc_html__( 'Opacity', 'ssc' ), 'selector' => '#search_form .input-group > div'),
                                    array('property' => 'margin', 'label' => esc_html__( 'Margin', 'ssc' ), 'selector' => '#search_form .input-group > div'),
                                    array('property' => 'padding', 'label' => esc_html__( 'Padding', 'ssc' ), 'selector' => '#search_form .input-group > div'),
                                    array('property' => 'border', 'label' => esc_html__( 'Border', 'ssc' ), 'selector' => '#search_form .input-group > div'),
                                    array('property' => 'border-radius', 'label' => esc_html__( 'Border Radius', 'ssc' ), 'selector' => '#search_form .input-group > div'),
                                ),
                                'Icons' => array(
                                    array('property' => 'background', 'selector' => 'i'),
                                    array('property' => 'text-align', 'label' => esc_html__( 'Text Align', 'ssc' ), 'selector' => 'i'),
                                    array('property' => 'margin', 'label' => esc_html__( 'Margin', 'ssc' ), 'selector' => 'i'),
                                    array('property' => 'padding', 'label' => esc_html__( 'Padding', 'ssc' ), 'selector' => 'i'),
                                    array('property' => 'border', 'label' => esc_html__( 'Border', 'ssc' ), 'selector' => 'i'),
                                    array('property' => 'border-radius', 'label' => esc_html__( 'Border Radius', 'ssc' ), 'selector' => 'i'),
                                    array('property' => 'width', 'label' => esc_html__( 'Width', 'ssc' ), 'selector' => 'i'),
                                    array('property' => 'height', 'label' => esc_html__( 'Height', 'ssc' ), 'selector' => 'i'),
                                    array('property' => 'float', 'label' => esc_html__( 'Float', 'ssc' ), 'selector' => 'i'),
                                    array('property' => 'display', 'label' => esc_html__( 'Display', 'ssc' ), 'selector' => 'i'),
                                    array('property' => 'box-shadow', 'label' => esc_html__( 'Box Shadow', 'ssc' ), 'selector' => 'i'),
                                    array('property' => 'opacity', 'label' => esc_html__( 'Opacity', 'ssc' ), 'selector' => 'i'),
                                ),
                                'Label' => array(
                                    array('property' => 'background', 'selector' => '.search-date-label, .search-date-label, .search-guests-label'),
                                    array('property' => 'color', 'label' => esc_html__( 'Color', 'ssc' ), 'selector' => '.search-date-label, .search-date-label, .search-guests-label'),
                                    array('property' => 'font-size', 'label' => esc_html__( 'Font Size', 'ssc' ), 'selector' => '.search-date-label, .search-date-label, .search-guests-label'),
                                    array('property' => 'line-height', 'label' => esc_html__( 'Line Height', 'ssc' ), 'selector' => '.search-date-label, .search-date-label, .search-guests-label'),
                                    array('property' => 'font-weight', 'label' => esc_html__( 'Font Weight', 'ssc' ), 'selector' => '.search-date-label, .search-date-label, .search-guests-label'),
                                    array('property' => 'font-style', 'label' => esc_html__( 'Font Style', 'ssc' ), 'selector' => '.search-date-label, .search-date-label, .search-guests-label'),
                                    array('property' => 'font-family', 'label' => esc_html__( 'Font Family', 'ssc' ), 'selector' => '.search-date-label, .search-date-label, .search-guests-label'),
                                    array('property' => 'text-align', 'label' => esc_html__( 'Text Align', 'ssc' ), 'selector' => '.search-date-label, .search-date-label, .search-guests-label'),
                                    array('property' => 'text-shadow', 'label' => esc_html__( 'Text Shadow', 'ssc' ), 'selector' => '.search-date-label, .search-date-label, .search-guests-label'),
                                    array('property' => 'text-transform', 'label' => esc_html__( 'Text Transform', 'ssc' ), 'selector' => '.search-date-label, .search-date-label, .search-guests-label'),
                                    array('property' => 'text-decoration', 'label' => esc_html__( 'Text Decoration', 'ssc' ), 'selector' => '.search-date-label, .search-date-label, .search-guests-label'),
                                    array('property' => 'letter-spacing', 'label' => esc_html__( 'Letter Spacing', 'ssc' ), 'selector' => '.search-date-label, .search-date-label, .search-guests-label'),
                                    array('property' => 'overflow', 'label' => esc_html__( 'Overflow', 'ssc' ), 'selector' => '.search-date-label, .search-date-label, .search-guests-label'),
                                    array('property' => 'float', 'label' => esc_html__( 'Float', 'ssc' ), 'selector' => '.search-date-label, .search-date-label, .search-guests-label'),
                                    array('property' => 'display', 'label' => esc_html__( 'Display', 'ssc' ), 'selector' => '.search-date-label, .search-date-label, .search-guests-label'),
                                    array('property' => 'word-break', 'label' => esc_html__( 'Word Break', 'ssc' ), 'selector' => '.search-date-label, .search-date-label, .search-guests-label'),
                                    array('property' => 'margin', 'label' => esc_html__( 'Margin', 'ssc' ), 'selector' => '.search-date-label, .search-date-label, .search-guests-label'),
                                    array('property' => 'padding', 'label' => esc_html__( 'Padding', 'ssc' ), 'selector' => '.search-date-label, .search-date-label, .search-guests-label'),
                                    array('property' => 'border', 'label' => esc_html__( 'Border', 'ssc' ), 'selector' => '.search-date-label, .search-date-label, .search-guests-label'),
                                    array('property' => 'border-radius', 'label' => esc_html__( 'Border Radius', 'ssc' ), 'selector' => '.search-date-label, .search-date-label, .search-guests-label'),
                                ),
                                'Date Wrap' => array(
                                    array('property' => 'background', 'selector' => 'div.search-date'),
                                    array('property' => 'color', 'label' => esc_html__( 'Color', 'ssc' ), 'selector' => 'div.search-date'),
                                    array('property' => 'font-size', 'label' => esc_html__( 'Font Size', 'ssc' ), 'selector' => 'div.search-date'),
                                    array('property' => 'line-height', 'label' => esc_html__( 'Line Height', 'ssc' ), 'selector' => 'div.search-date'),
                                    array('property' => 'font-weight', 'label' => esc_html__( 'Font Weight', 'ssc' ), 'selector' => 'div.search-date'),
                                    array('property' => 'font-style', 'label' => esc_html__( 'Font Style', 'ssc' ), 'selector' => 'div.search-date'),
                                    array('property' => 'font-family', 'label' => esc_html__( 'Font Family', 'ssc' ), 'selector' => 'div.search-date'),
                                    array('property' => 'text-align', 'label' => esc_html__( 'Text Align', 'ssc' ), 'selector' => 'div.search-date'),
                                    array('property' => 'text-shadow', 'label' => esc_html__( 'Text Shadow', 'ssc' ), 'selector' => 'div.search-date'),
                                    array('property' => 'text-transform', 'label' => esc_html__( 'Text Transform', 'ssc' ), 'selector' => 'div.search-date'),
                                    array('property' => 'text-decoration', 'label' => esc_html__( 'Text Decoration', 'ssc' ), 'selector' => 'div.search-date'),
                                    array('property' => 'letter-spacing', 'label' => esc_html__( 'Letter Spacing', 'ssc' ), 'selector' => 'div.search-date'),
                                    array('property' => 'overflow', 'label' => esc_html__( 'Overflow', 'ssc' ), 'selector' => 'div.search-date'),
                                    array('property' => 'float', 'label' => esc_html__( 'Float', 'ssc' ), 'selector' => 'div.search-date'),
                                    array('property' => 'display', 'label' => esc_html__( 'Display', 'ssc' ), 'selector' => 'div.search-date'),
                                    array('property' => 'word-break', 'label' => esc_html__( 'Word Break', 'ssc' ), 'selector' => 'div.search-date'),
                                    array('property' => 'margin', 'label' => esc_html__( 'Margin', 'ssc' ), 'selector' => 'div.search-date'),
                                    array('property' => 'padding', 'label' => esc_html__( 'Padding', 'ssc' ), 'selector' => 'div.search-date'),
                                    array('property' => 'border', 'label' => esc_html__( 'Border', 'ssc' ), 'selector' => 'div.search-date'),
                                    array('property' => 'border-radius', 'label' => esc_html__( 'Border Radius', 'ssc' ), 'selector' => 'div.search-date'),
                                ),
                                'Date' => array(
                                    array('property' => 'background', 'selector' => '.search_date'),
                                    array('property' => 'color', 'label' => esc_html__( 'Color', 'ssc' ), 'selector' => '.search_date'),
                                    array('property' => 'font-size', 'label' => esc_html__( 'Font Size', 'ssc' ), 'selector' => '.search_date'),
                                    array('property' => 'line-height', 'label' => esc_html__( 'Line Height', 'ssc' ), 'selector' => '.search_date'),
                                    array('property' => 'font-weight', 'label' => esc_html__( 'Font Weight', 'ssc' ), 'selector' => '.search_date'),
                                    array('property' => 'font-style', 'label' => esc_html__( 'Font Style', 'ssc' ), 'selector' => '.search_date'),
                                    array('property' => 'font-family', 'label' => esc_html__( 'Font Family', 'ssc' ), 'selector' => '.search_date'),
                                    array('property' => 'text-align', 'label' => esc_html__( 'Text Align', 'ssc' ), 'selector' => '.search_date'),
                                    array('property' => 'text-shadow', 'label' => esc_html__( 'Text Shadow', 'ssc' ), 'selector' => '.search_date'),
                                    array('property' => 'text-transform', 'label' => esc_html__( 'Text Transform', 'ssc' ), 'selector' => '.search_date'),
                                    array('property' => 'text-decoration', 'label' => esc_html__( 'Text Decoration', 'ssc' ), 'selector' => '.search_date'),
                                    array('property' => 'letter-spacing', 'label' => esc_html__( 'Letter Spacing', 'ssc' ), 'selector' => '.search_date'),
                                    array('property' => 'overflow', 'label' => esc_html__( 'Overflow', 'ssc' ), 'selector' => '.search_date'),
                                    array('property' => 'float', 'label' => esc_html__( 'Float', 'ssc' ), 'selector' => '.search_date'),
                                    array('property' => 'display', 'label' => esc_html__( 'Display', 'ssc' ), 'selector' => '.search_date'),
                                    array('property' => 'word-break', 'label' => esc_html__( 'Word Break', 'ssc' ), 'selector' => '.search_date'),
                                    array('property' => 'margin', 'label' => esc_html__( 'Margin', 'ssc' ), 'selector' => '.search_date'),
                                    array('property' => 'padding', 'label' => esc_html__( 'Padding', 'ssc' ), 'selector' => '.search_date'),
                                    array('property' => 'border', 'label' => esc_html__( 'Border', 'ssc' ), 'selector' => '.search_date'),
                                    array('property' => 'border-radius', 'label' => esc_html__( 'Border Radius', 'ssc' ), 'selector' => '.search_date'),
                                ),
                                'Guest Wrap' => array(
                                    array('property' => 'background', 'selector' => '.search_guests_field'),
                                    array('property' => 'color', 'label' => esc_html__( 'Color', 'ssc' ), 'selector' => '.search_guests_field'),
                                    array('property' => 'font-size', 'label' => esc_html__( 'Font Size', 'ssc' ), 'selector' => '.search_guests_field'),
                                    array('property' => 'line-height', 'label' => esc_html__( 'Line Height', 'ssc' ), 'selector' => '.search_guests_field'),
                                    array('property' => 'font-weight', 'label' => esc_html__( 'Font Weight', 'ssc' ), 'selector' => '.search_guests_field'),
                                    array('property' => 'font-style', 'label' => esc_html__( 'Font Style', 'ssc' ), 'selector' => '.search_guests_field'),
                                    array('property' => 'font-family', 'label' => esc_html__( 'Font Family', 'ssc' ), 'selector' => '.search_guests_field'),
                                    array('property' => 'text-align', 'label' => esc_html__( 'Text Align', 'ssc' ), 'selector' => '.search_guests_field'),
                                    array('property' => 'text-shadow', 'label' => esc_html__( 'Text Shadow', 'ssc' ), 'selector' => '.search_guests_field'),
                                    array('property' => 'text-transform', 'label' => esc_html__( 'Text Transform', 'ssc' ), 'selector' => '.search_guests_field'),
                                    array('property' => 'text-decoration', 'label' => esc_html__( 'Text Decoration', 'ssc' ), 'selector' => '.search_guests_field'),
                                    array('property' => 'letter-spacing', 'label' => esc_html__( 'Letter Spacing', 'ssc' ), 'selector' => '.search_guests_field'),
                                    array('property' => 'overflow', 'label' => esc_html__( 'Overflow', 'ssc' ), 'selector' => '.search_guests_field'),
                                    array('property' => 'float', 'label' => esc_html__( 'Float', 'ssc' ), 'selector' => '.search_guests_field'),
                                    array('property' => 'display', 'label' => esc_html__( 'Display', 'ssc' ), 'selector' => '.search_guests_field'),
                                    array('property' => 'word-break', 'label' => esc_html__( 'Word Break', 'ssc' ), 'selector' => '.search_guests_field'),
                                    array('property' => 'margin', 'label' => esc_html__( 'Margin', 'ssc' ), 'selector' => '.search_guests_field'),
                                    array('property' => 'padding', 'label' => esc_html__( 'Padding', 'ssc' ), 'selector' => '.search_guests_field'),
                                    array('property' => 'border', 'label' => esc_html__( 'Border', 'ssc' ), 'selector' => '.search_guests_field'),
                                    array('property' => 'border-radius', 'label' => esc_html__( 'Border Radius', 'ssc' ), 'selector' => '.search_guests_field'),
                                ),
                                'Guest' => array(
                                    array('property' => 'background', 'selector' => '.search_guests_title'),
                                    array('property' => 'color', 'label' => esc_html__( 'Color', 'ssc' ), 'selector' => '.search_guests_title'),
                                    array('property' => 'font-size', 'label' => esc_html__( 'Font Size', 'ssc' ), 'selector' => '.search_guests_title'),
                                    array('property' => 'line-height', 'label' => esc_html__( 'Line Height', 'ssc' ), 'selector' => '.search_guests_title'),
                                    array('property' => 'font-weight', 'label' => esc_html__( 'Font Weight', 'ssc' ), 'selector' => '.search_guests_title'),
                                    array('property' => 'font-style', 'label' => esc_html__( 'Font Style', 'ssc' ), 'selector' => '.search_guests_title'),
                                    array('property' => 'font-family', 'label' => esc_html__( 'Font Family', 'ssc' ), 'selector' => '.search_guests_title'),
                                    array('property' => 'text-align', 'label' => esc_html__( 'Text Align', 'ssc' ), 'selector' => '.search_guests_title'),
                                    array('property' => 'text-shadow', 'label' => esc_html__( 'Text Shadow', 'ssc' ), 'selector' => '.search_guests_title'),
                                    array('property' => 'text-transform', 'label' => esc_html__( 'Text Transform', 'ssc' ), 'selector' => '.search_guests_title'),
                                    array('property' => 'text-decoration', 'label' => esc_html__( 'Text Decoration', 'ssc' ), 'selector' => '.search_guests_title'),
                                    array('property' => 'letter-spacing', 'label' => esc_html__( 'Letter Spacing', 'ssc' ), 'selector' => '.search_guests_title'),
                                    array('property' => 'overflow', 'label' => esc_html__( 'Overflow', 'ssc' ), 'selector' => '.search_guests_title'),
                                    array('property' => 'float', 'label' => esc_html__( 'Float', 'ssc' ), 'selector' => '.search_guests_title'),
                                    array('property' => 'display', 'label' => esc_html__( 'Display', 'ssc' ), 'selector' => '.search_guests_title'),
                                    array('property' => 'word-break', 'label' => esc_html__( 'Word Break', 'ssc' ), 'selector' => '.search_guests_title'),
                                    array('property' => 'margin', 'label' => esc_html__( 'Margin', 'ssc' ), 'selector' => '.search_guests_title'),
                                    array('property' => 'padding', 'label' => esc_html__( 'Padding', 'ssc' ), 'selector' => '.search_guests_title'),
                                    array('property' => 'border', 'label' => esc_html__( 'Border', 'ssc' ), 'selector' => '.search_guests_title'),
                                    array('property' => 'border-radius', 'label' => esc_html__( 'Border Radius', 'ssc' ), 'selector' => '.search_guests_title'),
                                ),
                                'Button' => array(
                                    array('property' => 'background', 'selector' => '.babe-search-form button.btn-search'),
                                    array('property' => 'color', 'label' => esc_html__( 'Color', 'ssc' ), 'selector' => '.babe-search-form button.btn-search'),
                                    array('property' => 'font-size', 'label' => esc_html__( 'Font Size', 'ssc' ), 'selector' => '.babe-search-form button.btn-search'),
                                    array('property' => 'line-height', 'label' => esc_html__( 'Line Height', 'ssc' ), 'selector' => '.babe-search-form button.btn-search'),
                                    array('property' => 'font-weight', 'label' => esc_html__( 'Font Weight', 'ssc' ), 'selector' => '.babe-search-form button.btn-search'),
                                    array('property' => 'font-style', 'label' => esc_html__( 'Font Style', 'ssc' ), 'selector' => '.babe-search-form button.btn-search'),
                                    array('property' => 'font-family', 'label' => esc_html__( 'Font Family', 'ssc' ), 'selector' => '.babe-search-form button.btn-search'),
                                    array('property' => 'text-align', 'label' => esc_html__( 'Text Align', 'ssc' ), 'selector' => '.babe-search-form button.btn-search'),
                                    array('property' => 'text-shadow', 'label' => esc_html__( 'Text Shadow', 'ssc' ), 'selector' => '.babe-search-form button.btn-search'),
                                    array('property' => 'text-transform', 'label' => esc_html__( 'Text Transform', 'ssc' ), 'selector' => '.babe-search-form button.btn-search'),
                                    array('property' => 'text-decoration', 'label' => esc_html__( 'Text Decoration', 'ssc' ), 'selector' => '.babe-search-form button.btn-search'),
                                    array('property' => 'letter-spacing', 'label' => esc_html__( 'Letter Spacing', 'ssc' ), 'selector' => '.babe-search-form button.btn-search'),
                                    array('property' => 'overflow', 'label' => esc_html__( 'Overflow', 'ssc' ), 'selector' => '.babe-search-form button.btn-search'),
                                    array('property' => 'float', 'label' => esc_html__( 'Float', 'ssc' ), 'selector' => '.babe-search-form button.btn-search'),
                                    array('property' => 'display', 'label' => esc_html__( 'Display', 'ssc' ), 'selector' => '.babe-search-form button.btn-search'),
                                    array('property' => 'word-break', 'label' => esc_html__( 'Word Break', 'ssc' ), 'selector' => '.babe-search-form button.btn-search'),
                                    array('property' => 'margin', 'label' => esc_html__( 'Margin', 'ssc' ), 'selector' => '.babe-search-form button.btn-search'),
                                    array('property' => 'padding', 'label' => esc_html__( 'Padding', 'ssc' ), 'selector' => '.babe-search-form button.btn-search'),
                                    array('property' => 'border', 'label' => esc_html__( 'Border', 'ssc' ), 'selector' => '.babe-search-form button.btn-search'),
                                    array('property' => 'border-radius', 'label' => esc_html__( 'Border Radius', 'ssc' ), 'selector' => '.babe-search-form button.btn-search'),
                                ),
								'Button SVG' => array(
									array('property' => 'fill', 'label' => esc_html__( 'Color', 'ssc' ), 'selector' => '.babe-search-form button.btn-search svg'),
									array('property' => 'background', 'selector' => '.babe-search-form button.btn-search svg'),
									array('property' => 'width', 'label' => esc_html__( 'Width', 'ssc' ), 'selector' => '.babe-search-form button.btn-search svg'),
									array('property' => 'height', 'label' => esc_html__( 'Height', 'ssc' ), 'selector' => '.babe-search-form button.btn-search svg'),
									array('property' => 'float', 'label' => esc_html__( 'Float', 'ssc' ), 'selector' => '.babe-search-form button.btn-search svg'),
									array('property' => 'display', 'label' => esc_html__( 'Display', 'ssc' ), 'selector' => '.babe-search-form button.btn-search svg'),
									array('property' => 'margin', 'label' => esc_html__('Margin', 'ssc' ), 'selector' => '.babe-search-form button.btn-search svg'),
									array('property' => 'padding', 'label' =>esc_html__( 'Padding', 'ssc' ), 'selector' => '.babe-search-form button.btn-search svg'),
									array('property' => 'border', 'label' =>esc_html__( 'Padding', 'ssc' ), 'selector' => '.babe-search-form button.btn-search svg'),
									array('property' => 'border-radius', 'label' =>esc_html__( 'Padding', 'ssc' ), 'selector' => '.babe-search-form button.btn-search svg'),
									array('opacity' => 'border-radius', 'label' =>esc_html__( 'Padding', 'ssc' ), 'selector' => '.babe-search-form button.btn-search svg'),
								),
								'Button text' => array(
									array('property' => 'background', 'selector' => '.babe-search-form button.btn-search .text'),
									array('property' => 'color', 'label' => esc_html__( 'Color', 'ssc' ), 'selector' => '.babe-search-form button.btn-search .text'),
									array('property' => 'font-size', 'label' => esc_html__( 'Font Size', 'ssc' ), 'selector' => '.babe-search-form button.btn-search .text'),
									array('property' => 'line-height', 'label' => esc_html__( 'Line Height', 'ssc' ), 'selector' => '.babe-search-form button.btn-search .text'),
									array('property' => 'font-weight', 'label' => esc_html__( 'Font Weight', 'ssc' ), 'selector' => '.babe-search-form button.btn-search .text'),
									array('property' => 'font-style', 'label' => esc_html__( 'Font Style', 'ssc' ), 'selector' => '.babe-search-form button.btn-search .text'),
									array('property' => 'font-family', 'label' => esc_html__( 'Font Family', 'ssc' ), 'selector' => '.babe-search-form button.btn-search .text'),
									array('property' => 'text-align', 'label' => esc_html__( 'Text Align', 'ssc' ), 'selector' => '.babe-search-form button.btn-search .text'),
									array('property' => 'text-shadow', 'label' => esc_html__( 'Text Shadow', 'ssc' ), 'selector' => '.babe-search-form button.btn-search .text'),
									array('property' => 'text-transform', 'label' => esc_html__( 'Text Transform', 'ssc' ), 'selector' => '.babe-search-form button.btn-search .text'),
									array('property' => 'text-decoration', 'label' => esc_html__( 'Text Decoration', 'ssc' ), 'selector' => '.babe-search-form button.btn-search .text'),
									array('property' => 'letter-spacing', 'label' => esc_html__( 'Letter Spacing', 'ssc' ), 'selector' => '.babe-search-form button.btn-search .text'),
									array('property' => 'overflow', 'label' => esc_html__( 'Overflow', 'ssc' ), 'selector' => '.babe-search-form button.btn-search .text'),
									array('property' => 'float', 'label' => esc_html__( 'Float', 'ssc' ), 'selector' => '.babe-search-form button.btn-search .text'),
									array('property' => 'display', 'label' => esc_html__( 'Display', 'ssc' ), 'selector' => '.babe-search-form button.btn-search .text'),
									array('property' => 'word-break', 'label' => esc_html__( 'Word Break', 'ssc' ), 'selector' => '.babe-search-form button.btn-search .text'),
									array('property' => 'margin', 'label' => esc_html__( 'Margin', 'ssc' ), 'selector' => '.babe-search-form button.btn-search .text'),
									array('property' => 'padding', 'label' => esc_html__( 'Padding', 'ssc' ), 'selector' => '.babe-search-form button.btn-search .text'),
									array('property' => 'border', 'label' => esc_html__( 'Border', 'ssc' ), 'selector' => '.babe-search-form button.btn-search .text'),
									array('property' => 'border-radius', 'label' => esc_html__( 'Border Radius', 'ssc' ), 'selector' => '.babe-search-form button.btn-search .text'),
								),
							),

						)
					)
				),
				esc_html__( 'hover', 'ssc' ) => array(
					array(
						'name' => 'my-css-hover',
						'label' =>  esc_html__( 'Hover', 'ssc' ),
						'type' => 'css',
						'value' => '', // remove this if you do not need a default content
						'description' => esc_html__( 'Styles on hover', 'ssc' ),
						'options' => array(
							array(
								'screens' => "any,999,768,667,479",
                                'Box' => array(
                                    array('property' => 'background', 'selector' => '.babe-search-form:hover'),
                                    array('property' => 'display', 'label' => esc_html__( 'Display', 'ssc' ), 'selector' => '.babe-search-form:hover'),
                                    array('property' => 'float', 'label' => esc_html__( 'Float', 'ssc' ), 'selector' => '.babe-search-form:hover'),
                                    array('property' => 'max-width', 'label' => esc_html__( 'Max Width', 'ssc' ), 'selector' => '.babe-search-form:hover'),
                                    array('property' => 'width', 'label' => esc_html__( 'Width', 'ssc' ), 'selector' => '.babe-search-form:hover'),
                                    array('property' => 'height', 'label' => esc_html__( 'Height', 'ssc' ), 'selector' => '.babe-search-form:hover'),
                                    array('property' => 'box-shadow', 'label' => esc_html__( 'Box Shadow', 'ssc' ), 'selector' => '.babe-search-form:hover'),
                                    array('property' => 'opacity', 'label' => esc_html__( 'Opacity', 'ssc' ), 'selector' => '.babe-search-form:hover'),
                                    array('property' => 'margin', 'label' => esc_html__( 'Margin', 'ssc' ), 'selector' => '.babe-search-form:hover'),
                                    array('property' => 'padding', 'label' => esc_html__( 'Padding', 'ssc' ), 'selector' => '.babe-search-form:hover'),
                                    array('property' => 'border', 'label' => esc_html__( 'Border', 'ssc' ), 'selector' => '.babe-search-form:hover'),
                                    array('property' => 'border-radius', 'label' => esc_html__( 'Border Radius', 'ssc' ), 'selector' => '.babe-search-form:hover'),
                                ),
                                'Button' => array(
                                    array('property' => 'background', 'selector' => '#search-box button:hover'),
                                    array('property' => 'color', 'label' => esc_html__( 'Color', 'ssc' ), 'selector' => '#search-box button:hover'),
                                    array('property' => 'font-size', 'label' => esc_html__( 'Font Size', 'ssc' ), 'selector' => '#search-box button:hover'),
                                    array('property' => 'line-height', 'label' => esc_html__( 'Line Height', 'ssc' ), 'selector' => '#search-box button:hover'),
                                    array('property' => 'font-weight', 'label' => esc_html__( 'Font Weight', 'ssc' ), 'selector' => '#search-box button:hover'),
                                    array('property' => 'font-style', 'label' => esc_html__( 'Font Style', 'ssc' ), 'selector' => '#search-box button:hover'),
                                    array('property' => 'font-family', 'label' => esc_html__( 'Font Family', 'ssc' ), 'selector' => '#search-box button:hover'),
                                    array('property' => 'text-align', 'label' => esc_html__( 'Text Align', 'ssc' ), 'selector' => '#search-box button:hover'),
                                    array('property' => 'text-shadow', 'label' => esc_html__( 'Text Shadow', 'ssc' ), 'selector' => '#search-box button:hover'),
                                    array('property' => 'text-transform', 'label' => esc_html__( 'Text Transform', 'ssc' ), 'selector' => '#search-box button:hover'),
                                    array('property' => 'text-decoration', 'label' => esc_html__( 'Text Decoration', 'ssc' ), 'selector' => '#search-box button:hover'),
                                    array('property' => 'letter-spacing', 'label' => esc_html__( 'Letter Spacing', 'ssc' ), 'selector' => '#search-box button:hover'),
                                    array('property' => 'overflow', 'label' => esc_html__( 'Overflow', 'ssc' ), 'selector' => '#search-box button:hover'),
                                    array('property' => 'float', 'label' => esc_html__( 'Float', 'ssc' ), 'selector' => '#search-box button:hover'),
                                    array('property' => 'display', 'label' => esc_html__( 'Display', 'ssc' ), 'selector' => '#search-box button:hover'),
                                    array('property' => 'word-break', 'label' => esc_html__( 'Word Break', 'ssc' ), 'selector' => '#search-box button:hover'),
                                    array('property' => 'margin', 'label' => esc_html__( 'Margin', 'ssc' ), 'selector' => '#search-box button:hover'),
                                    array('property' => 'padding', 'label' => esc_html__( 'Padding', 'ssc' ), 'selector' => '#search-box button:hover'),
                                    array('property' => 'border', 'label' => esc_html__( 'Border', 'ssc' ), 'selector' => '#search-box button:hover'),
                                    array('property' => 'border-radius', 'label' => esc_html__( 'Border Radius', 'ssc' ), 'selector' => '#search-box button:hover'),
                                ),
                                'Button SVG' => array(
                                    array('property' => 'fill', 'label' => esc_html__( 'Color', 'ssc' ), 'selector' => '.babe-search-form button.btn-search:hover svg'),
                                    array('property' => 'background', 'selector' => '.babe-search-form button.btn-search:hover svg'),
                                    array('property' => 'width', 'label' => esc_html__( 'Width', 'ssc' ), 'selector' => '.babe-search-form button.btn-search:hover svg'),
                                    array('property' => 'height', 'label' => esc_html__( 'Height', 'ssc' ), 'selector' => '.babe-search-form button.btn-search:hover svg'),
                                    array('property' => 'float', 'label' => esc_html__( 'Float', 'ssc' ), 'selector' => '.babe-search-form button.btn-search:hover svg'),
                                    array('property' => 'display', 'label' => esc_html__( 'Display', 'ssc' ), 'selector' => '.babe-search-form button.btn-search:hover svg'),
                                    array('property' => 'margin', 'label' => esc_html__('Margin', 'ssc' ), 'selector' => '.babe-search-form button.btn-search:hover svg'),
                                    array('property' => 'padding', 'label' =>esc_html__( 'Padding', 'ssc' ), 'selector' => '.babe-search-form button.btn-search:hover svg'),
                                    array('property' => 'border', 'label' =>esc_html__( 'Padding', 'ssc' ), 'selector' => '.babe-search-form button.btn-search:hover svg'),
                                    array('property' => 'border-radius', 'label' =>esc_html__( 'Padding', 'ssc' ), 'selector' => '.babe-search-form button.btn-search:hover svg'),
                                    array('opacity' => 'border-radius', 'label' =>esc_html__( 'Padding', 'ssc' ), 'selector' => '.babe-search-form button.btn-search:hover svg'),
                                ),
                                'Button text' => array(
                                    array('property' => 'background', 'selector' => '.babe-search-form button.btn-search:hover .text'),
                                    array('property' => 'color', 'label' => esc_html__( 'Color', 'ssc' ), 'selector' => '.babe-search-form button.btn-search:hover .text'),
                                    array('property' => 'font-size', 'label' => esc_html__( 'Font Size', 'ssc' ), 'selector' => '.babe-search-form button.btn-search:hover .text'),
                                    array('property' => 'line-height', 'label' => esc_html__( 'Line Height', 'ssc' ), 'selector' => '.babe-search-form button.btn-search:hover .text'),
                                    array('property' => 'font-weight', 'label' => esc_html__( 'Font Weight', 'ssc' ), 'selector' => '.babe-search-form button.btn-search:hover .text'),
                                    array('property' => 'font-style', 'label' => esc_html__( 'Font Style', 'ssc' ), 'selector' => '.babe-search-form button.btn-search:hover .text'),
                                    array('property' => 'font-family', 'label' => esc_html__( 'Font Family', 'ssc' ), 'selector' => '.babe-search-form button.btn-search:hover .text'),
                                    array('property' => 'text-align', 'label' => esc_html__( 'Text Align', 'ssc' ), 'selector' => '.babe-search-form button.btn-search:hover .text'),
                                    array('property' => 'text-shadow', 'label' => esc_html__( 'Text Shadow', 'ssc' ), 'selector' => '.babe-search-form button.btn-search:hover .text'),
                                    array('property' => 'text-transform', 'label' => esc_html__( 'Text Transform', 'ssc' ), 'selector' => '.babe-search-form button.btn-search:hover .text'),
                                    array('property' => 'text-decoration', 'label' => esc_html__( 'Text Decoration', 'ssc' ), 'selector' => '.babe-search-form button.btn-search:hover .text'),
                                    array('property' => 'letter-spacing', 'label' => esc_html__( 'Letter Spacing', 'ssc' ), 'selector' => '.babe-search-form button.btn-search:hover .text'),
                                    array('property' => 'overflow', 'label' => esc_html__( 'Overflow', 'ssc' ), 'selector' => '.babe-search-form button.btn-search:hover .text'),
                                    array('property' => 'float', 'label' => esc_html__( 'Float', 'ssc' ), 'selector' => '.babe-search-form button.btn-search:hover .text'),
                                    array('property' => 'display', 'label' => esc_html__( 'Display', 'ssc' ), 'selector' => '.babe-search-form button.btn-search:hover .text'),
                                    array('property' => 'word-break', 'label' => esc_html__( 'Word Break', 'ssc' ), 'selector' => '.babe-search-form button.btn-search:hover .text'),
                                    array('property' => 'margin', 'label' => esc_html__( 'Margin', 'ssc' ), 'selector' => '.babe-search-form button.btn-search:hover .text'),
                                    array('property' => 'padding', 'label' => esc_html__( 'Padding', 'ssc' ), 'selector' => '.babe-search-form button.btn-search:hover .text'),
                                    array('property' => 'border', 'label' => esc_html__( 'Border', 'ssc' ), 'selector' => '.babe-search-form button.btn-search:hover .text'),
                                    array('property' => 'border-radius', 'label' => esc_html__( 'Border Radius', 'ssc' ), 'selector' => '.babe-search-form button.btn-search:hover .text'),
                                ),
							),

						)
					)
				),
//				esc_html__( 'styling', 'ssc' )  => array(
//					array()
//				),
//				'hover'  => array(),
//				'animate' => array(),
			),
		),
	) );
}

function ssc_babe_search_shortcode( $atts, $content = null ){
	extract( shortcode_atts( array(
		'title'             => '',
		'orientation'             => '',
		'date_from_label'      => '',
		'date_to_label'      => '',
		'guests_label'      => '',
		'guest_text'      => '',
		'guests_text'      => '',
		'button_title'      => '',
		'button_svg'      => '',
		'el_class' => '',

	),
		$atts ) );

	$wrp_classes = apply_filters( 'kc-el-class', $atts );

	$form_settings = array(
		'form_class' => 'active',
		'date_from_label' => $date_from_label,
		'date_to_label' => $date_to_label,
		'guests_label' => $guests_label,
		'guest_text' => $guest_text,
		'guests_text' => $guests_text,
		'button_title' => $button_title,
	);

	if( '' !== $button_svg) {
		$button_svg = ssc_process_media( $button_svg );
		$form_settings['button_icon'] = $button_svg;
	}

	return '<div class="ssc-babe-form ' . $el_class . ' '. $orientation . ' ' . implode( ' ', $wrp_classes ) . '">' . Atiframebuilder_Room::render_form( $title, $form_settings  ) . '</div>';
}

add_shortcode( 'ssc_babe_search', 'ssc_babe_search_shortcode' );